version: 2.1
jobs: 
  test: 
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Run test
          command: echo "Test was successful"
  build:
    steps:
      - run:
          name: Run
          command: echo "Build successful"
workflows:
  version: 2.1
  my_workflow:
    jobs:
      - test
      - build:
          requires:
            - test
