version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: Install packages
          command: |
            pip install -r requirements.txt
      - run:
          name: Test
          command: |
            python3 test.py
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
