version: 2.1
jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: Install packages
          command: |
            pip install -r requirements.txt
      - run:
          name: Test
          command: |
            python3 test.py
            echo "Test was successful"
  deploy:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      
      - setup_remote_docker

      - run:
          name: Install docker client
          command: |
            set -x
            VER="24.0.5-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Push image into Docker hub
          command: |
            docker build -t $DOCKER_HUB_USER_ID/$IMAGE_NAME:latest .
            echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER_ID" --password-stdin 
            docker push $DOCKER_HUB_USER_ID/$IMAGE_NAME:latest

workflows:
  version: 2.1
  my_app_workflow:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
